### ISSUE TITLE
Seeing more ads

### ISSUE THREAD

**Issue by Geczy** [LeonHeidelbach/ttv_adEraser#2]
Have this extension enabled and a stream keeps getting interrupted with ads

I think it's no longer working

**Comment by Geczy** [comment]
https://github.com/odensc/ttv-ublock/issues/21

**Comment by LeonHeidelbach** [comment]
I might have come up with an idea that could potentially make it less likely to see an ad or the purple screen. However, I will have to experiment around with the idea for a bit. As mentioned in the issue created on https://github.com/odensc/ttv-ublock/issues/21 my tests have also confirmed that blocking any gql requests will not impact the display of the purple screen since it is directly injected into the hls stream. I will keep you guys posted on my progress.

**Comment by LeonHeidelbach** [comment]
New working ad blocking methods have been implemented in the latest dev_build. You can try it out and let me know if it works for you. Note that there might still be some bugs in the dev_build.

https://github.com/LeonHeidelbach/ttv_adEraser/tree/dev_build
